services:
  web:
    build:
      context: .
      # Correct the path to your Dockerfile
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    # Important to bind/mount your codebase dir to /app dir for live reload
    volumes:
      - ./:/app